DTSSTCI 44 - Add sptribs case api and frontend
hmcts/cnp-api-docs pull request #349
Opened 2023-11-06 16:44 UTC by gmmagruder

### Jira link (if applicable)
https://tools.hmcts.net/jira/browse/DTSSTCI-44

### Change description ###
Added new ST group and sptribs-case-api amd sptribs-frontend to microservices.json. Also added st.html.

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2023-11-06 16:50 UTC, tomxelliott commented on docs/c4/hmcts.mdsl
> +   sptribs_frontend = container "Special Tribunals Frontend" ""
Can you add a description of the app in the second set of speech marks

2023-11-06 16:50 UTC, tomxelliott commented on docs/c4/hmcts.mdsl
> +   sptribs_case_api = container "Special Tribunal Case API" ""
Can you add a description of the app in the second set of speech marks

2023-11-06 16:52 UTC, tomxelliott commented on docs/microservices.json
> +      "description": "",
Can we add a short description please

2023-11-06 16:52 UTC, tomxelliott commented on docs/microservices.json
> +      "description": "",
Can we add a short description please

2023-11-06 16:52 UTC, tomxelliott requested changes
Just need some descriptions of the apps

2023-11-06 17:05 UTC, tomxelliott commented on docs/microservices.json
> +      "description": "Java service to deal with special tribunal case management system",
```suggestion
      "description": "Business logic for the management of Special Tribunals cases",
```

2023-11-06 17:06 UTC, tomxelliott commented on docs/c4/hmcts.mdsl
> +   sptribs_case_api = container "Special Tribunal Case API" "Java service to deal with special tribunal case management system"
```suggestion
   sptribs_case_api = container "Special Tribunal Case API" "Business logic for the management of Special Tribunals cases"
```

2023-11-06 17:23 UTC, gmmagruder commented on docs/microservices.json
> +      "description": "Java service to deal with special tribunal case management system",
Done

2023-11-07 10:18 UTC, tomxelliott approved these changes

2023-11-07 11:11 UTC, merged